models:
  qwen3-1.7b:
    repo_id: Qwen/Qwen3-1.7B
    local_path: ../Qwen/Qwen3-1.7B
  qwen3-4b-instruct:
    repo_id: Qwen/Qwen3-4B-Instruct-2507
    local_path: ../Qwen/Qwen3-4B-Instruct-2507
  qwen3-14b:
    repo_id: Qwen/Qwen3-14B
    local_path: ../Qwen/Qwen3-14B
  qwen3-32b:
    repo_id: Qwen/Qwen3-32B
    local_path: ../Qwen/Qwen3-32B
  llama3.1-8b:
    repo_id: meta-llama/Llama-3.1-8B-Instruct
    local_path: ../meta-llama/Llama-3.1-8B-Instruct
  llama3.3-70b:
    repo_id: meta-llama/Llama-3.3-70B-Instruct
    local_path: ../meta-llama/Llama-3.3-70B-Instruct
